global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/alert.rules'

scrape_configs:
  - job_name: 'sportstream-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8080']