ENVIRONMENT:
  NAME: local
NATS:
  RECONNECT_WAIT: "10s"
  CONSUMERS:
    ARTICLES:
      UPDATE:
        CONSUMER_NAME: "sportstream_docker_updated"
        CONSUMER_GROUP: "sportstream_docker"
        SUBJECT: "SPORTSTREAM.status.updated"
        STREAM: "SPORTSTREAM"
MESSAGE_QUEUE_PROCESSOR:
  MAX_RETRIES: 5
  LIMIT: 100
  WAIT: "10s"
MESSAGE_QUEUE:
  RECONNECTION_WAIT: "10s"


